package com.knetwork.forex.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FeatureAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeatureAllPropertiesEquals(Feature expected, Feature actual) {
        assertFeatureAutoGeneratedPropertiesEquals(expected, actual);
        assertFeatureAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeatureAllUpdatablePropertiesEquals(Feature expected, Feature actual) {
        assertFeatureUpdatableFieldsEquals(expected, actual);
        assertFeatureUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeatureAutoGeneratedPropertiesEquals(Feature expected, Feature actual) {
        assertThat(actual)
            .as("Verify Feature auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeatureUpdatableFieldsEquals(Feature expected, Feature actual) {
        assertThat(actual)
            .as("Verify Feature relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeatureUpdatableRelationshipsEquals(Feature expected, Feature actual) {
        assertThat(actual)
            .as("Verify Feature relationships")
            .satisfies(a -> assertThat(a.getBroker()).as("check broker").isEqualTo(expected.getBroker()));
    }
}
