package com.knetwork.forex.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InstrumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstrumentAllPropertiesEquals(Instrument expected, Instrument actual) {
        assertInstrumentAutoGeneratedPropertiesEquals(expected, actual);
        assertInstrumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstrumentAllUpdatablePropertiesEquals(Instrument expected, Instrument actual) {
        assertInstrumentUpdatableFieldsEquals(expected, actual);
        assertInstrumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstrumentAutoGeneratedPropertiesEquals(Instrument expected, Instrument actual) {
        assertThat(actual)
            .as("Verify Instrument auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstrumentUpdatableFieldsEquals(Instrument expected, Instrument actual) {
        assertThat(actual)
            .as("Verify Instrument relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstrumentUpdatableRelationshipsEquals(Instrument expected, Instrument actual) {
        assertThat(actual)
            .as("Verify Instrument relationships")
            .satisfies(a -> assertThat(a.getBroker()).as("check broker").isEqualTo(expected.getBroker()));
    }
}
