package com.actionnow.knetwork.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CoinAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoinAllPropertiesEquals(Coin expected, Coin actual) {
        assertCoinAutoGeneratedPropertiesEquals(expected, actual);
        assertCoinAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoinAllUpdatablePropertiesEquals(Coin expected, Coin actual) {
        assertCoinUpdatableFieldsEquals(expected, actual);
        assertCoinUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoinAutoGeneratedPropertiesEquals(Coin expected, Coin actual) {
        assertThat(actual)
            .as("Verify Coin auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoinUpdatableFieldsEquals(Coin expected, Coin actual) {
        assertThat(actual)
            .as("Verify Coin relevant properties")
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getValueEn()).as("check valueEn").isEqualTo(expected.getValueEn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoinUpdatableRelationshipsEquals(Coin expected, Coin actual) {
        // empty method
    }
}
