package com.actionnow.knetwork.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CryptoProAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoProAllPropertiesEquals(CryptoPro expected, CryptoPro actual) {
        assertCryptoProAutoGeneratedPropertiesEquals(expected, actual);
        assertCryptoProAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoProAllUpdatablePropertiesEquals(CryptoPro expected, CryptoPro actual) {
        assertCryptoProUpdatableFieldsEquals(expected, actual);
        assertCryptoProUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoProAutoGeneratedPropertiesEquals(CryptoPro expected, CryptoPro actual) {
        assertThat(actual)
            .as("Verify CryptoPro auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoProUpdatableFieldsEquals(CryptoPro expected, CryptoPro actual) {
        assertThat(actual)
            .as("Verify CryptoPro relevant properties")
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getValueEn()).as("check valueEn").isEqualTo(expected.getValueEn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoProUpdatableRelationshipsEquals(CryptoPro expected, CryptoPro actual) {
        // empty method
    }
}
