package com.actionnow.knetwork.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CryptoFeatureAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoFeatureAllPropertiesEquals(CryptoFeature expected, CryptoFeature actual) {
        assertCryptoFeatureAutoGeneratedPropertiesEquals(expected, actual);
        assertCryptoFeatureAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoFeatureAllUpdatablePropertiesEquals(CryptoFeature expected, CryptoFeature actual) {
        assertCryptoFeatureUpdatableFieldsEquals(expected, actual);
        assertCryptoFeatureUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoFeatureAutoGeneratedPropertiesEquals(CryptoFeature expected, CryptoFeature actual) {
        assertThat(actual)
            .as("Verify CryptoFeature auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoFeatureUpdatableFieldsEquals(CryptoFeature expected, CryptoFeature actual) {
        assertThat(actual)
            .as("Verify CryptoFeature relevant properties")
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getValueEn()).as("check valueEn").isEqualTo(expected.getValueEn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoFeatureUpdatableRelationshipsEquals(CryptoFeature expected, CryptoFeature actual) {
        // empty method
    }
}
