package com.actionnow.knetwork.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CryptoPaymentMethodAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoPaymentMethodAllPropertiesEquals(CryptoPaymentMethod expected, CryptoPaymentMethod actual) {
        assertCryptoPaymentMethodAutoGeneratedPropertiesEquals(expected, actual);
        assertCryptoPaymentMethodAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoPaymentMethodAllUpdatablePropertiesEquals(CryptoPaymentMethod expected, CryptoPaymentMethod actual) {
        assertCryptoPaymentMethodUpdatableFieldsEquals(expected, actual);
        assertCryptoPaymentMethodUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoPaymentMethodAutoGeneratedPropertiesEquals(CryptoPaymentMethod expected, CryptoPaymentMethod actual) {
        assertThat(actual)
            .as("Verify CryptoPaymentMethod auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoPaymentMethodUpdatableFieldsEquals(CryptoPaymentMethod expected, CryptoPaymentMethod actual) {
        assertThat(actual)
            .as("Verify CryptoPaymentMethod relevant properties")
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getValueEn()).as("check valueEn").isEqualTo(expected.getValueEn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoPaymentMethodUpdatableRelationshipsEquals(CryptoPaymentMethod expected, CryptoPaymentMethod actual) {
        // empty method
    }
}
