package com.actionnow.knetwork.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CryptoConAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoConAllPropertiesEquals(CryptoCon expected, CryptoCon actual) {
        assertCryptoConAutoGeneratedPropertiesEquals(expected, actual);
        assertCryptoConAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoConAllUpdatablePropertiesEquals(CryptoCon expected, CryptoCon actual) {
        assertCryptoConUpdatableFieldsEquals(expected, actual);
        assertCryptoConUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoConAutoGeneratedPropertiesEquals(CryptoCon expected, CryptoCon actual) {
        assertThat(actual)
            .as("Verify CryptoCon auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoConUpdatableFieldsEquals(CryptoCon expected, CryptoCon actual) {
        assertThat(actual)
            .as("Verify CryptoCon relevant properties")
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getValueEn()).as("check valueEn").isEqualTo(expected.getValueEn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCryptoConUpdatableRelationshipsEquals(CryptoCon expected, CryptoCon actual) {
        // empty method
    }
}
