package com.actionnow.knetwork.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CustomerSupportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerSupportAllPropertiesEquals(CustomerSupport expected, CustomerSupport actual) {
        assertCustomerSupportAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomerSupportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerSupportAllUpdatablePropertiesEquals(CustomerSupport expected, CustomerSupport actual) {
        assertCustomerSupportUpdatableFieldsEquals(expected, actual);
        assertCustomerSupportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerSupportAutoGeneratedPropertiesEquals(CustomerSupport expected, CustomerSupport actual) {
        assertThat(actual)
            .as("Verify CustomerSupport auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerSupportUpdatableFieldsEquals(CustomerSupport expected, CustomerSupport actual) {
        assertThat(actual)
            .as("Verify CustomerSupport relevant properties")
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getValueEn()).as("check valueEn").isEqualTo(expected.getValueEn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerSupportUpdatableRelationshipsEquals(CustomerSupport expected, CustomerSupport actual) {
        // empty method
    }
}
