package com.actionnow.knetwork.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class KnowledgeTagAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeTagAllPropertiesEquals(KnowledgeTag expected, KnowledgeTag actual) {
        assertKnowledgeTagAutoGeneratedPropertiesEquals(expected, actual);
        assertKnowledgeTagAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeTagAllUpdatablePropertiesEquals(KnowledgeTag expected, KnowledgeTag actual) {
        assertKnowledgeTagUpdatableFieldsEquals(expected, actual);
        assertKnowledgeTagUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeTagAutoGeneratedPropertiesEquals(KnowledgeTag expected, KnowledgeTag actual) {
        assertThat(actual)
            .as("Verify KnowledgeTag auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeTagUpdatableFieldsEquals(KnowledgeTag expected, KnowledgeTag actual) {
        assertThat(actual)
            .as("Verify KnowledgeTag relevant properties")
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getValueEn()).as("check valueEn").isEqualTo(expected.getValueEn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeTagUpdatableRelationshipsEquals(KnowledgeTag expected, KnowledgeTag actual) {
        // empty method
    }
}
