package com.actionnow.knetwork.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LanguageSupportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLanguageSupportAllPropertiesEquals(LanguageSupport expected, LanguageSupport actual) {
        assertLanguageSupportAutoGeneratedPropertiesEquals(expected, actual);
        assertLanguageSupportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLanguageSupportAllUpdatablePropertiesEquals(LanguageSupport expected, LanguageSupport actual) {
        assertLanguageSupportUpdatableFieldsEquals(expected, actual);
        assertLanguageSupportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLanguageSupportAutoGeneratedPropertiesEquals(LanguageSupport expected, LanguageSupport actual) {
        assertThat(actual)
            .as("Verify LanguageSupport auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLanguageSupportUpdatableFieldsEquals(LanguageSupport expected, LanguageSupport actual) {
        assertThat(actual)
            .as("Verify LanguageSupport relevant properties")
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getValueEn()).as("check valueEn").isEqualTo(expected.getValueEn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLanguageSupportUpdatableRelationshipsEquals(LanguageSupport expected, LanguageSupport actual) {
        // empty method
    }
}
