package com.actionnow.knetwork.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlatformAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformAllPropertiesEquals(Platform expected, Platform actual) {
        assertPlatformAutoGeneratedPropertiesEquals(expected, actual);
        assertPlatformAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformAllUpdatablePropertiesEquals(Platform expected, Platform actual) {
        assertPlatformUpdatableFieldsEquals(expected, actual);
        assertPlatformUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformAutoGeneratedPropertiesEquals(Platform expected, Platform actual) {
        assertThat(actual)
            .as("Verify Platform auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformUpdatableFieldsEquals(Platform expected, Platform actual) {
        assertThat(actual)
            .as("Verify Platform relevant properties")
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getValueEn()).as("check valueEn").isEqualTo(expected.getValueEn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformUpdatableRelationshipsEquals(Platform expected, Platform actual) {
        // empty method
    }
}
