package com.actionnow.knetwork.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SecurityFeatureAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecurityFeatureAllPropertiesEquals(SecurityFeature expected, SecurityFeature actual) {
        assertSecurityFeatureAutoGeneratedPropertiesEquals(expected, actual);
        assertSecurityFeatureAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecurityFeatureAllUpdatablePropertiesEquals(SecurityFeature expected, SecurityFeature actual) {
        assertSecurityFeatureUpdatableFieldsEquals(expected, actual);
        assertSecurityFeatureUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecurityFeatureAutoGeneratedPropertiesEquals(SecurityFeature expected, SecurityFeature actual) {
        assertThat(actual)
            .as("Verify SecurityFeature auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecurityFeatureUpdatableFieldsEquals(SecurityFeature expected, SecurityFeature actual) {
        assertThat(actual)
            .as("Verify SecurityFeature relevant properties")
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getValueEn()).as("check valueEn").isEqualTo(expected.getValueEn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecurityFeatureUpdatableRelationshipsEquals(SecurityFeature expected, SecurityFeature actual) {
        // empty method
    }
}
