package com.actionnow.knetwork.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SupportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupportAllPropertiesEquals(Support expected, Support actual) {
        assertSupportAutoGeneratedPropertiesEquals(expected, actual);
        assertSupportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupportAllUpdatablePropertiesEquals(Support expected, Support actual) {
        assertSupportUpdatableFieldsEquals(expected, actual);
        assertSupportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupportAutoGeneratedPropertiesEquals(Support expected, Support actual) {
        assertThat(actual)
            .as("Verify Support auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupportUpdatableFieldsEquals(Support expected, Support actual) {
        assertThat(actual)
            .as("Verify Support relevant properties")
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getValueEn()).as("check valueEn").isEqualTo(expected.getValueEn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupportUpdatableRelationshipsEquals(Support expected, Support actual) {
        // empty method
    }
}
